---
- name: Gather and display router information
  hosts: mikrotik
  gather_facts: false
  tasks:

  - name: Gather system identity
    community.routeros.command:
      commands:
        - /system identity print
    register: system_identity


  - name: Gather facts
    community.routeros.facts:

  - name: Collect data for table
    set_fact:
      device_data: "{{ device_data | default([]) + [{'ip': ansible_host, 'name': system_identity.stdout_lines[0]}] }}"

  - name: Display table of devices
    debug:
      msg: |
        Devices Table:
        {% for device in device_data %}
        - IP: {{ device.ip }}, Name: {{ device.name }}
        {% endfor %}

